# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-amazon-athena-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-amazon-rds-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-amazon-redshift-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-asynchronous-invocation-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-chat-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-claude3-image-analysis-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-claude3-multi-modal-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-claude3-streaming-response-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-csv-chatbot-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-document-comparison-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/amazon-bedrock-document-generator-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-genai-dynamic-prompting-explained-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-guardrails-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-image-generation-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-knowledgebases-rag-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-langchain-rag-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-model-customization" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-model-playground-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-rag-kendra-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-rag-opensearch-serverless-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-speech-to-text-chat-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-streaming-response-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-summarization-long-document-poc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/genai-quickstart-pocs-python/genai-quickstart-pocs-python/amazon-bedrock-video-chapter-creator-poc" # Location of package manifests
    schedule:
      interval: "daily"
      
