s3_bucket = "" # S3 Bucket Name where videos live (and subtitles, if they already exist)
cloudfront_hostname = "" # CloudFront Hostname for the S3 bucket (e.g. d1w7f0v2oz4t8.cloudfront.net)
opensearch_endpoint = "" #OpenSearch Endpoint URL (e.g. xxxxxxxxxxxx.us-east-1.aoss.amazonaws.com)
bedrock_region = "us-east-1" #Region used for Bedrock APIs
opensearch_region = "us-east-1" #Region the OpenSearch Collection Exists
opensearch_index = "" #OpenSearch Index Name 
aws_profile_name = "" #AWS CLI Profile Name